name: Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code!
        uses: actions/checkout@v2
      - name: Deploy to Heroku!
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          branch: main
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: festiva-ucf
          heroku_email: ${{secrets.HEROKU_EMAIL}}