name: Publish stories if changed

on:
  push:
    branches:
      - main
    paths:
      - src/components/**
  workflow_call:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "☁️ checkout repository"
        uses: actions/checkout@v2

      - name: "🔧 setup node"
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16

      - name: "🔧 install npm@latest"
        run: npm i -g npm@latest

      - name: "📦 install dependencies"
        uses: bahmutov/npm-install@v1

      - name: "🚀 deploy static"
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Replace with the path to your build output directory
          commit_message: ${{ github.event.head_commit.message }}
          enable_jekyll: false
