name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Test and Build
        run: |
          # Install dependencies, run tests, and build the application
          npm install
          npm test
          npm run build

      - name: Create Semantic Release
        uses: cycloidio/semantic-release@v0.7.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
